pygments: true
exclude: ["config.rb", "deploy.rb", "README.md", "Rakefile", "Procfile", "Gemfile", "Gemfile.lock"]
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
